### PR TITLE
Remove bashisms

### PR DESCRIPTION
**Pull request by pickfire**
Use #!/bin/sh

### CODE REVIEW

**Comment by 9ary** [comment]
What about the other example? Also would `#!/bin/sh -e` work instead of `set -e`? I know it works with bash but not sure about POSIX sh.

**Comment by pickfire** [comment]
That's good, `checkbashisms` didn't detect anything, from what I know `set -e` is valid.

**Comment by 9ary** [comment]
I'm talking about putting it on the shebang instead of an extra command.

**Comment by pickfire** [comment]
Yes, it's okay.

**Comment by 9ary** [comment]
Then please use it and fix the second example.

**Comment by pickfire** [comment]
@9ary T_T I am fixing it now already

**Comment by 9ary** [comment]
:thumbsup:

**Pull request merged**
